# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

scenario_a01_001:
  percentage_of_patients: 0.25
  persons:
    main_patient:
      age:
        from: 20
        to: 60
      gender: M
      first_name: "scenario_a01_001"
  pathway:
    - admission:
        loc: WardA01
    - delay:
        from: 30m
        to: 60m
    - discharge: {}

scenario_b01_001:
  percentage_of_patients: 0.25
  persons:
    main_patient:
      age:
        from: 20
        to: 60
      gender: M
      first_name: "scenario_b01_001"
  pathway:
    - admission:
        loc: WardB01
    - delay:
        from: 30m
        to: 60m
    - discharge: {}

scenario_c01_001:
  percentage_of_patients: 0.25
  persons:
    main_patient:
      age:
        from: 20
        to: 60
      gender: M
      first_name: "scenario_c01_001"
  pathway:
    - admission:
        loc: WardC01
    - delay:
        from: 30m
        to: 60m
    - discharge: {}

scenario_d01_001:
  percentage_of_patients: 0.25
  persons:
    main_patient:
      age:
        from: 20
        to: 60
      gender: M
      first_name: "scenario_d01_001"
  pathway:
    - admission:
        loc: WardD01
    - delay:
        from: 30m
        to: 60m
    - discharge: {}